INSERT INTO TBGERCADEMPRESA (NUMCPFCNPJ, TIPOPESSOA, NOMEFANTASIA, RAZAOSOCIAL, POSSUIINSESTADUAL, INSESTADUAL, INSMUNICIPAL, ID_CNAE, ID_REGIMETRIBUTARIO, ID_REGIMEESPECIALTRIB, EMAIL, NUMTELEFONE, NUMCELULAR, SITE, LOGRADOUROCEP, LOGRADOURO, LOGRADOURONUM, LOGRADOUROCOMP, LOGRADOUROBAIRRO, LOGRADOUROUF, LOGRADOUROCIDADE, DTACADASTRO, DTAATUALIZACAO)
                     VALUES ('07292603645', 'F', 'Seti Sistemas', 'Seti Sistemas Ltda', NULL, NULL, NULL, NULL, NULL, NULL, 'dileno.ssantos@gmail.com', 0, 0, 'www.setisistemas.com', 31535522, 'Rua Corretor Juventino de Jesus', 71, 'Apto 701, B3', 'Candelária', 'MG', 'Belo Horizonte', '2019-01-13 17:37:13', NULL);

COMMIT WORK;
