INSERT INTO TBGERCADUSUARIOS (ID, NOME, LOGIN, SENHA, ID_GRUPO, STATUS, DTACADASTRO, EMAIL)
                      VALUES (1, 'DILENO SILVA DOS SANTOS', 'DILENO', 'Å`øqüX­—', 0, 'S', '2019-01-06 22:16:38', 'dileno.ssantos@gmail.com');

COMMIT WORK;
