USE [dbSetiFramework]
GO

/****** Object:  Table [dbo].[TBSETIFORM]    Script Date: 25/03/2018 23:08:15 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[TBSETIFORM](
	[ID] [int] NOT NULL IDENTITY(1,1),
	[FORMNAME] [varchar](100) NOT NULL,
	[FORMCAPTION] [varchar](100) NULL,
	[FORMTAG] [int] NULL,
	[STATUS] [char](1) NULL
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[TBSETIFORM] ADD  CONSTRAINT [DF_TBSETIFORM_FORMTAG]  DEFAULT ((0)) FOR [FORMTAG]
GO

ALTER TABLE [dbo].[TBSETIFORM] ADD  CONSTRAINT [DF_TBSETIFORM_STATUS]  DEFAULT ('S') FOR [STATUS]
GO


