INSERT INTO TBUF (ID, UF, DESCRICAO, REGIAO)
          VALUES (11, 'RO', 'Rondônia', 'NORTE');
INSERT INTO TBUF (ID, UF, DESCRICAO, REGIAO)
          VALUES (12, 'AC', 'Acre', 'NORTE');
INSERT INTO TBUF (ID, UF, DESCRICAO, REGIAO)
          VALUES (13, 'AM', 'Amazonas', 'NORTE');
INSERT INTO TBUF (ID, UF, DESCRICAO, REGIAO)
          VALUES (14, 'RR', 'Roraima', 'NORTE');
INSERT INTO TBUF (ID, UF, DESCRICAO, REGIAO)
          VALUES (15, 'PA', 'Pará', 'NORTE');
INSERT INTO TBUF (ID, UF, DESCRICAO, REGIAO)
          VALUES (16, 'AP', 'Amapá', 'NORTE');
INSERT INTO TBUF (ID, UF, DESCRICAO, REGIAO)
          VALUES (17, 'TO', 'Tocantis', 'NORTE');
INSERT INTO TBUF (ID, UF, DESCRICAO, REGIAO)
          VALUES (21, 'MA', 'Maranhão', 'NORDESTE');
INSERT INTO TBUF (ID, UF, DESCRICAO, REGIAO)
          VALUES (22, 'PI', 'Piaui', 'NORDESTE');
INSERT INTO TBUF (ID, UF, DESCRICAO, REGIAO)
          VALUES (23, 'CE', 'Ceará', 'NORDESTE');
INSERT INTO TBUF (ID, UF, DESCRICAO, REGIAO)
          VALUES (24, 'RN', 'Rio Grande do Norte', 'NORDESTE');
INSERT INTO TBUF (ID, UF, DESCRICAO, REGIAO)
          VALUES (25, 'PB', 'Paraíba', 'NORDESTE');
INSERT INTO TBUF (ID, UF, DESCRICAO, REGIAO)
          VALUES (26, 'PE', 'Pernambuco', 'NORDESTE');
INSERT INTO TBUF (ID, UF, DESCRICAO, REGIAO)
          VALUES (27, 'AL', 'Alagoas', 'NORDESTE');
INSERT INTO TBUF (ID, UF, DESCRICAO, REGIAO)
          VALUES (28, 'SE', 'Sergipe', 'NORDESTE');
INSERT INTO TBUF (ID, UF, DESCRICAO, REGIAO)
          VALUES (29, 'BA', 'Bahia', 'NORDESTE');
INSERT INTO TBUF (ID, UF, DESCRICAO, REGIAO)
          VALUES (31, 'MG', 'Minas Gerais', 'SUDESTE');
INSERT INTO TBUF (ID, UF, DESCRICAO, REGIAO)
          VALUES (32, 'ES', 'Espírito Santo', 'SUDESTE');
INSERT INTO TBUF (ID, UF, DESCRICAO, REGIAO)
          VALUES (33, 'RJ', 'Rio de Janeiro', 'SUDESTE');
INSERT INTO TBUF (ID, UF, DESCRICAO, REGIAO)
          VALUES (35, 'SP', 'São Paulo', 'SUDESTE');
INSERT INTO TBUF (ID, UF, DESCRICAO, REGIAO)
          VALUES (41, 'PR', 'Paraná', 'SUL');
INSERT INTO TBUF (ID, UF, DESCRICAO, REGIAO)
          VALUES (42, 'SC', 'Santa Catarina', 'SUL');
INSERT INTO TBUF (ID, UF, DESCRICAO, REGIAO)
          VALUES (43, 'RS', 'Rio Grande do Sil', 'SUL');
INSERT INTO TBUF (ID, UF, DESCRICAO, REGIAO)
          VALUES (50, 'MS', 'Mato Grosso do Sul', 'CENTRO-OESTE');
INSERT INTO TBUF (ID, UF, DESCRICAO, REGIAO)
          VALUES (51, 'MT', 'Mato Grosso', 'CENTRO-OESTE');
INSERT INTO TBUF (ID, UF, DESCRICAO, REGIAO)
          VALUES (52, 'GO', 'Goiás', 'CENTRO-OESTE');
INSERT INTO TBUF (ID, UF, DESCRICAO, REGIAO)
          VALUES (53, 'DF', 'Distrito Federal', 'CENTRO-OESTE');

COMMIT WORK;
