INSERT INTO tbproviderparams (
ID,CODPARAM,TABLENAME,FIELDNAME,FIELDNAMEALIAS,FIELDCAPTION,SIZEFORGRID,VISIBLEINGRID,SPNAME,VIEWNAME,
QUERYNAME,OBS) values (
GEN_ID(gen_id_providerparams,1),3,'TBCADFUNCIONARIOS','ID','ID','Cod.Vendedor',8,'S',null,null,null,null);

INSERT INTO tbproviderparams (
ID,CODPARAM,TABLENAME,FIELDNAME,FIELDNAMEALIAS,FIELDCAPTION,SIZEFORGRID,VISIBLEINGRID,SPNAME,VIEWNAME,
QUERYNAME,OBS) values (
GEN_ID(gen_id_providerparams,1),3,'TBCADFUNCIONARIOS','NOME','NOME','Nome',35,'S',null,null,null,null);

INSERT INTO tbproviderparams (
ID,CODPARAM,TABLENAME,FIELDNAME,FIELDNAMEALIAS,FIELDCAPTION,SIZEFORGRID,VISIBLEINGRID,SPNAME,VIEWNAME,
QUERYNAME,OBS) values (
GEN_ID(gen_id_providerparams,1),3,'TBCADFUNCIONARIOS','CODIGOINTERNO','CODIGOINTERNO','Cod.Interno',15,'S',null,null,null,null);

INSERT INTO tbproviderparams (
ID,CODPARAM,TABLENAME,FIELDNAME,FIELDNAMEALIAS,FIELDCAPTION,SIZEFORGRID,VISIBLEINGRID,SPNAME,VIEWNAME,
QUERYNAME,OBS) values (
GEN_ID(gen_id_providerparams,1),3,'TBCADFUNCIONARIOS','CPFCNPJ','CPFCNPJ','CPF/CNPJ',15,'S',null,null,null,null);

INSERT INTO tbproviderparams (
ID,CODPARAM,TABLENAME,FIELDNAME,FIELDNAMEALIAS,FIELDCAPTION,SIZEFORGRID,VISIBLEINGRID,SPNAME,VIEWNAME,
QUERYNAME,OBS) values (
GEN_ID(gen_id_providerparams,1),3,'TBCADFUNCIONARIOS','NUMTELEFONE','NUMTELEFONE','Num.Telefone',15,'S',null,null,null,null);

INSERT INTO tbproviderparams (
ID,CODPARAM,TABLENAME,FIELDNAME,FIELDNAMEALIAS,FIELDCAPTION,SIZEFORGRID,VISIBLEINGRID,SPNAME,VIEWNAME,
QUERYNAME,OBS) values (
GEN_ID(gen_id_providerparams,1),3,'TBCADFUNCIONARIOS','NUMCELULAR','NUMCELULAR','Num.Celular',15,'S',null,null,null,null);

INSERT INTO tbproviderparams (
ID,CODPARAM,TABLENAME,FIELDNAME,FIELDNAMEALIAS,FIELDCAPTION,SIZEFORGRID,VISIBLEINGRID,SPNAME,VIEWNAME,
QUERYNAME,OBS) values (
GEN_ID(gen_id_providerparams,1),3,'TBCADFUNCIONARIOS','DATANIVERSARIO','DATANIVERSARIO','Dta.aniversario',15,'S',null,null,null,null);

INSERT INTO tbproviderparams (
ID,CODPARAM,TABLENAME,FIELDNAME,FIELDNAMEALIAS,FIELDCAPTION,SIZEFORGRID,VISIBLEINGRID,SPNAME,VIEWNAME,
QUERYNAME,OBS) values (
GEN_ID(gen_id_providerparams,1),3,'TBCADFUNCIONARIOS','DATCADASTRO','DATCADASTRO','Dta.Cadastro',15,'S',null,null,null,null);

INSERT INTO tbproviderparams (
ID,CODPARAM,TABLENAME,FIELDNAME,FIELDNAMEALIAS,FIELDCAPTION,SIZEFORGRID,VISIBLEINGRID,SPNAME,VIEWNAME,
QUERYNAME,OBS) values (
GEN_ID(gen_id_providerparams,1),3,'TBCADFUNCIONARIOS','DATULTMOVIMENTACAO','DATULTMOVIMENTACAO','Dta.Movimentacao',15,'S',null,null,null,null);

INSERT INTO tbproviderparams (
ID,CODPARAM,TABLENAME,FIELDNAME,FIELDNAMEALIAS,FIELDCAPTION,SIZEFORGRID,VISIBLEINGRID,SPNAME,VIEWNAME,
QUERYNAME,OBS) values (
GEN_ID(gen_id_providerparams,1),3,'TBCADFUNCIONARIOS','OBSERVACAO','OBSERVACAO','Obs.',50,'S',null,null,null,null);

INSERT INTO tbproviderparams (
ID,CODPARAM,TABLENAME,FIELDNAME,FIELDNAMEALIAS,FIELDCAPTION,SIZEFORGRID,VISIBLEINGRID,SPNAME,VIEWNAME,
QUERYNAME,OBS) values (
GEN_ID(gen_id_providerparams,1),3,'TBCADFUNCIONARIOS','LOGRADOUROCEP','LOGRADOUROCEP','CEP.',8,'S',null,null,null,null);

INSERT INTO tbproviderparams (
ID,CODPARAM,TABLENAME,FIELDNAME,FIELDNAMEALIAS,FIELDCAPTION,SIZEFORGRID,VISIBLEINGRID,SPNAME,VIEWNAME,
QUERYNAME,OBS) values (
GEN_ID(gen_id_providerparams,1),3,'TBCADFUNCIONARIOS','LOGRADOURO','LOGRADOURO','Logradouro',50,'S',null,null,null,null);

INSERT INTO tbproviderparams (
ID,CODPARAM,TABLENAME,FIELDNAME,FIELDNAMEALIAS,FIELDCAPTION,SIZEFORGRID,VISIBLEINGRID,SPNAME,VIEWNAME,
QUERYNAME,OBS) values (
GEN_ID(gen_id_providerparams,1),3,'TBCADFUNCIONARIOS','LOGRADOURONUM','LOGRADOURONUM','Num.',8,'S',null,null,null,null);

INSERT INTO tbproviderparams (
ID,CODPARAM,TABLENAME,FIELDNAME,FIELDNAMEALIAS,FIELDCAPTION,SIZEFORGRID,VISIBLEINGRID,SPNAME,VIEWNAME,
QUERYNAME,OBS) values (
GEN_ID(gen_id_providerparams,1),3,'TBCADFUNCIONARIOS','LOGRADOUROCOMP','LOGRADOUROCOMP','Comp.',8,'S',null,null,null,null);

INSERT INTO tbproviderparams (
ID,CODPARAM,TABLENAME,FIELDNAME,FIELDNAMEALIAS,FIELDCAPTION,SIZEFORGRID,VISIBLEINGRID,SPNAME,VIEWNAME,
QUERYNAME,OBS) values (
GEN_ID(gen_id_providerparams,1),3,'TBCADFUNCIONARIOS','LOGRADOUROBAIRRO','LOGRADOUROBAIRRO','Bairro',35,'S',null,null,null,null);

INSERT INTO tbproviderparams (
ID,CODPARAM,TABLENAME,FIELDNAME,FIELDNAMEALIAS,FIELDCAPTION,SIZEFORGRID,VISIBLEINGRID,SPNAME,VIEWNAME,
QUERYNAME,OBS) values (
GEN_ID(gen_id_providerparams,1),3,'TBCADFUNCIONARIOS','LOGRADOUROUF','LOGRADOUROUF','UF',8,'S',null,null,null,null);

INSERT INTO tbproviderparams (
ID,CODPARAM,TABLENAME,FIELDNAME,FIELDNAMEALIAS,FIELDCAPTION,SIZEFORGRID,VISIBLEINGRID,SPNAME,VIEWNAME,
QUERYNAME,OBS) values (
GEN_ID(gen_id_providerparams,1),3,'TBCADFUNCIONARIOS','LOGRADOUROCIDADE','LOGRADOUROCIDADE','Cidade',35,'S',null,null,null,null);

INSERT INTO tbproviderparams (
ID,CODPARAM,TABLENAME,FIELDNAME,FIELDNAMEALIAS,FIELDCAPTION,SIZEFORGRID,VISIBLEINGRID,SPNAME,VIEWNAME,
QUERYNAME,OBS) values (
GEN_ID(gen_id_providerparams,1),3,'TBCADFUNCIONARIOS','DATADMISSAO','DATADMISSAO','Dta.Admissao',8,'S',null,null,null,null);

INSERT INTO tbproviderparams (
ID,CODPARAM,TABLENAME,FIELDNAME,FIELDNAMEALIAS,FIELDCAPTION,SIZEFORGRID,VISIBLEINGRID,SPNAME,VIEWNAME,
QUERYNAME,OBS) values (
GEN_ID(gen_id_providerparams,1),3,'TBCADFUNCIONARIOS','DATDESLIGAMENTO','DATDESLIGAMENTO','Dta.Desligamento',8,'S',null,null,null,null);

INSERT INTO tbproviderparams (
ID,CODPARAM,TABLENAME,FIELDNAME,FIELDNAMEALIAS,FIELDCAPTION,SIZEFORGRID,VISIBLEINGRID,SPNAME,VIEWNAME,
QUERYNAME,OBS) values (
GEN_ID(gen_id_providerparams,1),3,'TBCADFUNCIONARIOS','VENDEDOR','VENDEDOR','Vendedor',8,'S',null,null,null,null);

INSERT INTO tbproviderparams (
ID,CODPARAM,TABLENAME,FIELDNAME,FIELDNAMEALIAS,FIELDCAPTION,SIZEFORGRID,VISIBLEINGRID,SPNAME,VIEWNAME,
QUERYNAME,OBS) values (
GEN_ID(gen_id_providerparams,1),3,'TBCADFUNCIONARIOS','TECNICO','TECNICO','Tecnico',8,'S',null,null,null,null);

INSERT INTO tbproviderparams (
ID,CODPARAM,TABLENAME,FIELDNAME,FIELDNAMEALIAS,FIELDCAPTION,SIZEFORGRID,VISIBLEINGRID,SPNAME,VIEWNAME,
QUERYNAME,OBS) values (
GEN_ID(gen_id_providerparams,1),3,'TBCADFUNCIONARIOS','STATUS','STATUS','Status',8,'S',null,null,null,null);


