INSERT INTO tbproviderparams (
ID,CODPARAM,TABLENAME,FIELDNAME,FIELDNAMEALIAS,FIELDCAPTION,SIZEFORGRID,VISIBLEINGRID,SPNAME,VIEWNAME,
QUERYNAME,OBS) values (
GEN_ID(gen_id_providerparams,1),4,'TBCADFUNCIONARIOS','ID','ID','Cod.Vendedor',8,'S',null,null,null,null);

INSERT INTO tbproviderparams (
ID,CODPARAM,TABLENAME,FIELDNAME,FIELDNAMEALIAS,FIELDCAPTION,SIZEFORGRID,VISIBLEINGRID,SPNAME,VIEWNAME,
QUERYNAME,OBS) values (
GEN_ID(gen_id_providerparams,1),4,'TBCADFUNCIONARIOS','NOME','NOME','Nome',35,'S',null,null,null,null);

INSERT INTO tbproviderparams (
ID,CODPARAM,TABLENAME,FIELDNAME,FIELDNAMEALIAS,FIELDCAPTION,SIZEFORGRID,VISIBLEINGRID,SPNAME,VIEWNAME,
QUERYNAME,OBS) values (
GEN_ID(gen_id_providerparams,1),4,'TBCADFUNCIONARIOS','CODIGOINTERNO','CODIGOINTERNO','Cod.Interno',15,'S',null,null,null,null);

INSERT INTO tbproviderparams (
ID,CODPARAM,TABLENAME,FIELDNAME,FIELDNAMEALIAS,FIELDCAPTION,SIZEFORGRID,VISIBLEINGRID,SPNAME,VIEWNAME,
QUERYNAME,OBS) values (
GEN_ID(gen_id_providerparams,1),4,'TBCADFUNCIONARIOS','CPFCNPJ','CPFCNPJ','CPF/CNPJ',15,'S',null,null,null,null);

INSERT INTO tbproviderparams (
ID,CODPARAM,TABLENAME,FIELDNAME,FIELDNAMEALIAS,FIELDCAPTION,SIZEFORGRID,VISIBLEINGRID,SPNAME,VIEWNAME,
QUERYNAME,OBS) values (
GEN_ID(gen_id_providerparams,1),4,'TBCADFUNCIONARIOS','NUMTELEFONE','NUMTELEFONE','Num.Telefone',15,'S',null,null,null,null);

INSERT INTO tbproviderparams (
ID,CODPARAM,TABLENAME,FIELDNAME,FIELDNAMEALIAS,FIELDCAPTION,SIZEFORGRID,VISIBLEINGRID,SPNAME,VIEWNAME,
QUERYNAME,OBS) values (
GEN_ID(gen_id_providerparams,1),4,'TBCADFUNCIONARIOS','NUMCELULAR','NUMCELULAR','Num.Celular',15,'S',null,null,null,null);


