--REGIOES

INSERT INTO tbproviderparams (
ID,CODPARAM,TABLENAME,FIELDNAME,FIELDNAMEALIAS,FIELDCAPTION,SIZEFORGRID,VISIBLEINGRID,SPNAME,VIEWNAME,
QUERYNAME,OBS) values (
GEN_ID(gen_id_providerparams,1),5,'TBCADREGIOES','ID','ID','Cod.Regiao',8,'S',null,null,null,null);

INSERT INTO tbproviderparams (
ID,CODPARAM,TABLENAME,FIELDNAME,FIELDNAMEALIAS,FIELDCAPTION,SIZEFORGRID,VISIBLEINGRID,SPNAME,VIEWNAME,
QUERYNAME,OBS) values (
GEN_ID(gen_id_providerparams,1),5,'TBCADREGIOES','DESCRICAO','DESCRICAO','Descricao',35,'S',null,null,null,null);

INSERT INTO tbproviderparams (
ID,CODPARAM,TABLENAME,FIELDNAME,FIELDNAMEALIAS,FIELDCAPTION,SIZEFORGRID,VISIBLEINGRID,SPNAME,VIEWNAME,
QUERYNAME,OBS) values (
GEN_ID(gen_id_providerparams,1),5,'TBCADREGIOES','OBS','OBS','Obs.',80,'S',null,null,null,null);
