SET TERM ^ ;

CREATE OR ALTER PROCEDURE SP_REL_CONTROLEVENDAMANUALFICHA (
    ID_VENDAMANUAL INTEGER )
RETURNS (
     NOME1 VARCHAR(100)     ,NOME2 VARCHAR(100)     ,NOME3 VARCHAR(100)
    ,NOME4 VARCHAR(100)     ,NOME5 VARCHAR(100)     ,NOME6 VARCHAR(100)
    ,NOME7 VARCHAR(100)     ,NOME8 VARCHAR(100)     ,NOME9 VARCHAR(100)
    ,NOME10 VARCHAR(100)    ,NOME11 VARCHAR(100)    ,NOME12 VARCHAR(100)
    ,NOME13 VARCHAR(100)    ,NOME14 VARCHAR(100)    ,NOME15 VARCHAR(100)
    ,NOME16 VARCHAR(100)    

    ,QTDESTOQUE1 BIGINT     ,QTDESTOQUE2 BIGINT     ,QTDESTOQUE3 BIGINT
    ,QTDESTOQUE4 BIGINT     ,QTDESTOQUE5 BIGINT     ,QTDESTOQUE6 BIGINT
    ,QTDESTOQUE7 BIGINT     ,QTDESTOQUE8 BIGINT     ,QTDESTOQUE9 BIGINT
    ,QTDESTOQUE10 BIGINT    ,QTDESTOQUE11 BIGINT    ,QTDESTOQUE12 BIGINT
    ,QTDESTOQUE13 BIGINT    ,QTDESTOQUE14 BIGINT    ,QTDESTOQUE15 BIGINT
    ,QTDESTOQUE16 BIGINT

    ,QTDVENDA1 BIGINT       ,QTDVENDA2 BIGINT       ,QTDVENDA3 BIGINT
    ,QTDVENDA4 BIGINT       ,QTDVENDA5 BIGINT       ,QTDVENDA6 BIGINT
    ,QTDVENDA7 BIGINT       ,QTDVENDA8 BIGINT       ,QTDVENDA9 BIGINT
    ,QTDVENDA10 BIGINT      ,QTDVENDA11 BIGINT      ,QTDVENDA12 BIGINT
    ,QTDVENDA13 BIGINT      ,QTDVENDA14 BIGINT      ,QTDVENDA15 BIGINT
    ,QTDVENDA16 BIGINT                

    ,VLRVENDA1 NUMERIC(15,2)    ,VLRVENDA2 NUMERIC(15,2)
    ,VLRVENDA3 NUMERIC(15,2)    ,VLRVENDA4 NUMERIC(15,2)
    ,VLRVENDA5 NUMERIC(15,2)    ,VLRVENDA6 NUMERIC(15,2)
    ,VLRVENDA7 NUMERIC(15,2)    ,VLRVENDA8 NUMERIC(15,2)
    ,VLRVENDA9 NUMERIC(15,2)    ,VLRVENDA10 NUMERIC(15,2)
    ,VLRVENDA11 NUMERIC(15,2)   ,VLRVENDA12 NUMERIC(15,2)
    ,VLRVENDA13 NUMERIC(15,2)   ,VLRVENDA14 NUMERIC(15,2)
    ,VLRVENDA15 NUMERIC(15,2)   ,VLRVENDA16 NUMERIC(15,2)    

    ,VLRTOTAL1 NUMERIC(15,2)    ,VLRTOTAL2 NUMERIC(15,2)
    ,VLRTOTAL3 NUMERIC(15,2)    ,VLRTOTAL4 NUMERIC(15,2)
    ,VLRTOTAL5 NUMERIC(15,2)    ,VLRTOTAL6 NUMERIC(15,2)
    ,VLRTOTAL7 NUMERIC(15,2)    ,VLRTOTAL8 NUMERIC(15,2)
    ,VLRTOTAL9 NUMERIC(15,2)    ,VLRTOTAL10 NUMERIC(15,2)
    ,VLRTOTAL11 NUMERIC(15,2)   ,VLRTOTAL12 NUMERIC(15,2)
    ,VLRTOTAL13 NUMERIC(15,2)   ,VLRTOTAL14 NUMERIC(15,2)
    ,VLRTOTAL15 NUMERIC(15,2)   ,VLRTOTAL16 NUMERIC(15,2)
) AS
BEGIN
        FOR 
        SELECT
            CASE WHEN SEQUENCE = 1 THEN NOME END AS NOME1_
            ,CASE WHEN SEQUENCE = 2 THEN NOME END AS NOME2_
            ,CASE WHEN SEQUENCE = 3 THEN NOME END AS NOME3_
            ,CASE WHEN SEQUENCE = 4 THEN NOME END AS NOME4_
            ,CASE WHEN SEQUENCE = 5 THEN NOME END AS NOME5_
            ,CASE WHEN SEQUENCE = 6 THEN NOME END AS NOME6_
            ,CASE WHEN SEQUENCE = 7 THEN NOME END AS NOME7_
            ,CASE WHEN SEQUENCE = 8 THEN NOME END AS NOME8_
            ,CASE WHEN SEQUENCE = 9 THEN NOME END AS NOME9_
            ,CASE WHEN SEQUENCE = 10 THEN NOME END AS NOME10_
            ,CASE WHEN SEQUENCE = 11 THEN NOME END AS NOME11_
            ,CASE WHEN SEQUENCE = 12 THEN NOME END AS NOME12_
            ,CASE WHEN SEQUENCE = 13 THEN NOME END AS NOME13_
            ,CASE WHEN SEQUENCE = 14 THEN NOME END AS NOME14_
            ,CASE WHEN SEQUENCE = 15 THEN NOME END AS NOME15_
            ,CASE WHEN SEQUENCE = 16 THEN NOME END AS NOME16_
    
            ,CASE WHEN SEQUENCE = 1 THEN QTDESTOQUE END AS QTDESTOQUE1_
            ,CASE WHEN SEQUENCE = 2 THEN QTDESTOQUE END AS QTDESTOQUE2_
            ,CASE WHEN SEQUENCE = 3 THEN QTDESTOQUE END AS QTDESTOQUE3_
            ,CASE WHEN SEQUENCE = 4 THEN QTDESTOQUE END AS QTDESTOQUE4_
            ,CASE WHEN SEQUENCE = 5 THEN QTDESTOQUE END AS QTDESTOQUE5_
            ,CASE WHEN SEQUENCE = 6 THEN QTDESTOQUE END AS QTDESTOQUE6_
            ,CASE WHEN SEQUENCE = 7 THEN QTDESTOQUE END AS QTDESTOQUE7_
            ,CASE WHEN SEQUENCE = 8 THEN QTDESTOQUE END AS QTDESTOQUE8_
            ,CASE WHEN SEQUENCE = 9 THEN QTDESTOQUE END AS QTDESTOQUE9_
            ,CASE WHEN SEQUENCE = 10 THEN QTDESTOQUE END AS QTDESTOQUE10_
            ,CASE WHEN SEQUENCE = 11 THEN QTDESTOQUE END AS QTDESTOQUE11_
            ,CASE WHEN SEQUENCE = 12 THEN QTDESTOQUE END AS QTDESTOQUE12_
            ,CASE WHEN SEQUENCE = 13 THEN QTDESTOQUE END AS QTDESTOQUE13_
            ,CASE WHEN SEQUENCE = 14 THEN QTDESTOQUE END AS QTDESTOQUE14_
            ,CASE WHEN SEQUENCE = 15 THEN QTDESTOQUE END AS QTDESTOQUE15_
            ,CASE WHEN SEQUENCE = 16 THEN QTDESTOQUE END AS QTDESTOQUE16_
            
            ,CASE WHEN SEQUENCE = 1 THEN QTDVENDA END AS QTDVENDA1_
            ,CASE WHEN SEQUENCE = 2 THEN QTDVENDA END AS QTDVENDA2_
            ,CASE WHEN SEQUENCE = 3 THEN QTDVENDA END AS QTDVENDA3_
            ,CASE WHEN SEQUENCE = 4 THEN QTDVENDA END AS QTDVENDA4_
            ,CASE WHEN SEQUENCE = 5 THEN QTDVENDA END AS QTDVENDA5_
            ,CASE WHEN SEQUENCE = 6 THEN QTDVENDA END AS QTDVENDA6_
            ,CASE WHEN SEQUENCE = 7 THEN QTDVENDA END AS QTDVENDA7_
            ,CASE WHEN SEQUENCE = 8 THEN QTDVENDA END AS QTDVENDA8_
            ,CASE WHEN SEQUENCE = 9 THEN QTDVENDA END AS QTDVENDA9_
            ,CASE WHEN SEQUENCE = 10 THEN QTDVENDA END AS QTDVENDA10_
            ,CASE WHEN SEQUENCE = 11 THEN QTDVENDA END AS QTDVENDA11_
            ,CASE WHEN SEQUENCE = 12 THEN QTDVENDA END AS QTDVENDA12_
            ,CASE WHEN SEQUENCE = 13 THEN QTDVENDA END AS QTDVENDA13_
            ,CASE WHEN SEQUENCE = 14 THEN QTDVENDA END AS QTDVENDA14_
            ,CASE WHEN SEQUENCE = 15 THEN QTDVENDA END AS QTDVENDA15_
            ,CASE WHEN SEQUENCE = 16 THEN QTDVENDA END AS QTDVENDA16_    
            
            ,CASE WHEN SEQUENCE = 1 THEN VLRVENDA END AS VLRVENDA1_
            ,CASE WHEN SEQUENCE = 2 THEN VLRVENDA END AS VLRVENDA2_
            ,CASE WHEN SEQUENCE = 3 THEN VLRVENDA END AS VLRVENDA3_
            ,CASE WHEN SEQUENCE = 4 THEN VLRVENDA END AS VLRVENDA4_
            ,CASE WHEN SEQUENCE = 5 THEN VLRVENDA END AS VLRVENDA5_
            ,CASE WHEN SEQUENCE = 6 THEN VLRVENDA END AS VLRVENDA6_
            ,CASE WHEN SEQUENCE = 7 THEN VLRVENDA END AS VLRVENDA7_
            ,CASE WHEN SEQUENCE = 8 THEN VLRVENDA END AS VLRVENDA8_
            ,CASE WHEN SEQUENCE = 9 THEN VLRVENDA END AS VLRVENDA9_
            ,CASE WHEN SEQUENCE = 10 THEN VLRVENDA END AS VLRVENDA10_
            ,CASE WHEN SEQUENCE = 11 THEN VLRVENDA END AS VLRVENDA11_
            ,CASE WHEN SEQUENCE = 12 THEN VLRVENDA END AS VLRVENDA12_
            ,CASE WHEN SEQUENCE = 13 THEN VLRVENDA END AS VLRVENDA13_
            ,CASE WHEN SEQUENCE = 14 THEN VLRVENDA END AS VLRVENDA14_
            ,CASE WHEN SEQUENCE = 15 THEN VLRVENDA END AS VLRVENDA15_
            ,CASE WHEN SEQUENCE = 16 THEN VLRVENDA END AS VLRVENDA16_    
    
            ,CASE WHEN SEQUENCE = 1 THEN VLRTOTAL END AS VLRTOTAL1_
            ,CASE WHEN SEQUENCE = 2 THEN VLRTOTAL END AS VLRTOTAL2_
            ,CASE WHEN SEQUENCE = 3 THEN VLRTOTAL END AS VLRTOTAL3_
            ,CASE WHEN SEQUENCE = 4 THEN VLRTOTAL END AS VLRTOTAL4_
            ,CASE WHEN SEQUENCE = 5 THEN VLRTOTAL END AS VLRTOTAL5_
            ,CASE WHEN SEQUENCE = 6 THEN VLRTOTAL END AS VLRTOTAL6_
            ,CASE WHEN SEQUENCE = 7 THEN VLRTOTAL END AS VLRTOTAL7_
            ,CASE WHEN SEQUENCE = 8 THEN VLRTOTAL END AS VLRTOTAL8_
            ,CASE WHEN SEQUENCE = 9 THEN VLRTOTAL END AS VLRTOTAL9_
            ,CASE WHEN SEQUENCE = 10 THEN VLRTOTAL END AS VLRTOTAL10_
            ,CASE WHEN SEQUENCE = 11 THEN VLRTOTAL END AS VLRTOTAL11_
            ,CASE WHEN SEQUENCE = 12 THEN VLRTOTAL END AS VLRTOTAL12_
            ,CASE WHEN SEQUENCE = 13 THEN VLRTOTAL END AS VLRTOTAL13_
            ,CASE WHEN SEQUENCE = 14 THEN VLRTOTAL END AS VLRTOTAL14_
            ,CASE WHEN SEQUENCE = 15 THEN VLRTOTAL END AS VLRTOTAL15_
            ,CASE WHEN SEQUENCE = 16 THEN VLRTOTAL END AS VLRTOTAL16_            

        FROM
        (
            SELECT                                                     
                FIRST 16
                    NEXT VALUE FOR TMP_SEQUENCE AS SEQUENCIA
                ,P.NOME
                ,I.QTDESTOQUE
                ,I.QTDVENDA
                ,I.VLRVENDA
                ,I.VLRTOTAL
            FROM TBCADPRODUTOS P                                       
            LEFT JOIN  TBVENDAMANUAL_ITENS I ON P.ID = I.ID_PRODUTO
            AND I.ID_VENDAMANUAL = :ID_VENDAMANUAL
            WHERE 1 = 1
        ) A

    INTO
         :NOME1		,:NOME2		,:NOME3		
		,:NOME4		,:NOME5		,:NOME6
		,:NOME7		,:NOME8     ,:NOME9
		,:NOME10	,:NOME11	,:NOME12
		,:NOME13	,:NOME14	,:NOME15
		,:NOME16
		
        ,:QTDESTOQUE1	,:QTDESTOQUE2
		,:QTDESTOQUE3	,:QTDESTOQUE4
		,:QTDESTOQUE5   ,:QTDESTOQUE6
		,:QTDESTOQUE7	,:QTDESTOQUE8
		,:QTDESTOQUE9	,:QTDESTOQUE10
        ,:QTDESTOQUE11	,:QTDESTOQUE12
		,:QTDESTOQUE13	,:QTDESTOQUE14
		,:QTDESTOQUE15	,:QTDESTOQUE16        
		
        ,:QTDVENDA1		,:QTDVENDA2		,:QTDVENDA3		
		,:QTDVENDA4		,:QTDVENDA5		,:QTDVENDA6
		,:QTDVENDA7		,:QTDVENDA8		,:QTDVENDA9
		,:QTDVENDA10	,:QTDVENDA11	,:QTDVENDA12
		,:QTDVENDA13	,:QTDVENDA14	,:QTDVENDA15
		,:QTDVENDA16                
		
        ,:VLRVENDA1		,:VLRVENDA2		,:VLRVENDA3
		,:VLRVENDA4		,:VLRVENDA5		,:VLRVENDA6
		,:VLRVENDA7		,:VLRVENDA8	    ,:VLRVENDA9
		,:VLRVENDA10	,:VLRVENDA11	,:VLRVENDA12
		,:VLRVENDA13	,:VLRVENDA14	,:VLRVENDA15
		,:VLRVENDA16    
		
		,:VLRTOTAL1		,:VLRTOTAL2		,:VLRTOTAL3		
		,:VLRTOTAL4		,:VLRTOTAL5		,:VLRTOTAL6		
		,:VLRTOTAL7		,:VLRTOTAL8     ,:VLRTOTAL9		
		,:VLRTOTAL10	,:VLRTOTAL11	,:VLRTOTAL12	
		,:VLRTOTAL13	,:VLRTOTAL14	,:VLRTOTAL15	
		,:VLRTOTAL16    
    DO
    SUSPEND;
END^
SET TERM ; ^
    
/*
GRANT SELECT ON TBCADPRODUTOS TO PROCEDURE SP_REL_CONTROLEVENDAMANUALFICHA; 
GRANT SELECT ON TBVENDAMANUAL_ITENS TO PROCEDURE SP_REL_CONTROLEVENDAMANUALFICHA;

GRANT EXECUTE ON PROCEDURE SP_REL_CONTROLEVENDAMANUALFICHA TO SYSDBA;
*/












    
    
    
    
    
    
    
