/*
SELECT * FROM tbproject P

SELECT * FROM tbformsframework

SELECT * FROM tbformsproject
*/

SELECT
         P.ID AS PROJECT_ID
        ,P.NAME AS PROJECT_NAME
        ,P.DESCRIPTION AS PROJECT_DESCRIPTION
        ,P.STATUS AS PROJECT_STATUS
        ,P.DTACREATION AS PROJECT_DTACREATION
        ,F.ID AS FORMSFRAM_ID
        ,F.FORMNAME AS FORMSFRAM_NAME
        ,F.FORMCAPTION AS FORMSFRAM_CAPTION
        ,F.FORMTAG AS FORMSFRAM_TAG
        ,F.FORMSTATUS AS FORMSFRAM_STATUS
        ,F.IDPROJECT AS FORMSFRAM_IDPROJECT
        ,F.DTACREATION AS FORMSFRAM_DTACREATION
        ,F.IDFILE AS FORMSFRAM_IDFILE
        ,F.CODE AS FORMSFRAM_CODE
        ,F.PARENTIDPROJECT AS FORMSFRAM_PARENTIDPROJECT
        ,F.PARENTFORMID AS FORMSFRAM_PARENTFORMID
FROM TBPROJECT P
LEFT JOIN TBFORMSFRAMEWORK F ON F.IDPROJECT = P.ID

WHERE P.STATUS = 'S'

