Use dbSetiFramework;

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:		Dileno S Santos
-- Create date: 30/03/2018
-- Description:	Rotina para inserir ou atualizar informações do form selecionado no SETIFRAMEWORK.
-- =============================================
ALTER PROCEDURE [dbo].[SP_RecordFormInfo]  @FormName Varchar(100), @FormCaption Varchar(100), @FormTag Int, @Status Char(1)
AS
BEGIN
	SET NOCOUNT ON;

	IF (@FORMNAME <> '') BEGIN	
		DECLARE @FormName1 Varchar(100)
		SET @FormName1 = 'FRMTESTEHERANCA'
		SELECT	 
				MAX(ID) AS ID
				,FORMNAME	
				,FORMCAPTION	
				,FORMTAG	
				,STATUS				
				,MAX(CREATEDATE) AS CREATEDATE
		INTO #TBSETIFORM
		FROM DBSETIFRAMEWORK..TBSETIFORM WITH(NOLOCK)
		WHERE FORMNAME = @FormName1
		GROUP BY FORMNAME	
				,FORMCAPTION	
				,FORMTAG	
				,STATUS
		;
		
		IF (SELECT COUNT(*) FROM DBSETIFRAMEWORK..TBSETIFORM WITH(NOLOCK)) > 0
		BEGIN
			DECLARE @PID INT;
			DECLARE @PFORMNAME VARCHAR(100);
			DECLARE @PFORMCAPTION VARCHAR(100);
			DECLARE @PFORMTAG INT;
			DECLARE @PSTATUS CHAR(1);
			DECLARE @PCREATEDATE DATETIME;

			DECLARE CCFORM CURSOR FOR
			SELECT	ID		
					,FORMNAME	
					,FORMCAPTION	
					,FORMTAG	
					,STATUS
					,CREATEDATE
			FROM #TBSETIFORM

			OPEN CCFORM 
			FETCH NEXT FROM CCFORM INTO @PID, @PFORMNAME, @PFORMCAPTION, @PFORMTAG, @PSTATUS, @PCREATEDATE

			WHILE @@FETCH_STATUS = 0
			BEGIN
				IF (@FormCaption <> @PFORMCAPTION) 
				BEGIN
					UPDATE DBSETIFRAMEWORK..TBSETIFORM SET FORMCAPTION = @FormCaption 
						WHERE (ID = @PID) AND (FORMNAME = @FormName) 
				END
				IF (@FormTag <> @PFORMTAG) 
				BEGIN
					UPDATE DBSETIFRAMEWORK..TBSETIFORM SET FORMTAG = @FormTag 
						WHERE (ID = @PID) AND (FORMNAME = @FormName) 
				END
			END



		END



				
	END

END
GO

TRUNCATE TABLE DBSETIFRAMEWORK..TBSETIFORM

INSERT INTO DBSETIFRAMEWORK..TBSETIFORM (FORMNAME,FORMCAPTION,FORMTAG,STATUS) VALUES ('FRMMAIN',	'frmMain',	0,	'S');
INSERT INTO DBSETIFRAMEWORK..TBSETIFORM (FORMNAME,FORMCAPTION,FORMTAG,STATUS) VALUES ('FRMSTANDARDREG',	'Cadastro Padrão',	0,	'S');
INSERT INTO DBSETIFRAMEWORK..TBSETIFORM (FORMNAME,FORMCAPTION,FORMTAG,STATUS) VALUES ('FRMDEFAULTSEARCH',	'Pesquisa',	0,	'S');
INSERT INTO DBSETIFRAMEWORK..TBSETIFORM (FORMNAME,FORMCAPTION,FORMTAG,STATUS) VALUES ('FRMPATTERN',	'frmPattern',	0,	'S');
INSERT INTO DBSETIFRAMEWORK..TBSETIFORM (FORMNAME,FORMCAPTION,FORMTAG,STATUS) VALUES ('FRMTESTEHERANCA',	'Tela de Teste',	0,	'S');

SELECT * FROM DBSETIFRAMEWORK..TBSETIFORM WITH(NOLOCK)