program SetiCommercialManager;
{Não remover a linha abaixo
ngmm,,,,,,,,  n,n,,,klçk .´0 ~., mZXSACCSCVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVCVVBBBBBBBBS
}
uses
  Vcl.Forms,
  Windows,
  Vcl.StdCtrls,
  Vcl.Controls,
  ufrmForms in 'frameworkFiles\views\ufrmForms.pas' {frmForms},
  ufrmLogin in 'frameworkFiles\views\ufrmLogin.pas' {frmLogin},
  ufrmMain in 'frameworkFiles\views\ufrmMain.pas' {frmMain},
  ufrmPattern in 'frameworkFiles\views\ufrmPattern.pas' {frmPattern},
  ufrmSplash in 'frameworkFiles\views\ufrmSplash.pas' {frmSplash},
  ufrmStandardReg in 'frameworkFiles\views\ufrmStandardReg.pas' {frmStandardReg},
  ufrmTesteHeranca in 'frameworkFiles\views\ufrmTesteHeranca.pas' {frmTesteHeranca},
  ufrmTestePesquisa in 'frameworkFiles\views\ufrmTestePesquisa.pas' {frmTestePesquisa},
  ufrmTestePesquisa2 in 'frameworkFiles\views\ufrmTestePesquisa2.pas' {frmTestePesquisa2},
  ufrmToLocate in 'frameworkFiles\views\ufrmToLocate.pas' {frmToLocate},
  ufrmCadClientes in 'views\ufrmCadClientes.pas' {frmCadClientes},
  ufrmCadFornecedor in 'views\ufrmCadFornecedor.pas' {frmCadFornecedor},
  ufrmCadGrupoProdutos in 'views\ufrmCadGrupoProdutos.pas' {frmCadGrupoProdutos},
  ufrmCadMarcasProdutos in 'views\ufrmCadMarcasProdutos.pas' {frmCadMarcasProdutos},
  ufrmCadModeloProdutos in 'views\ufrmCadModeloProdutos.pas' {frmCadModeloProdutos},
  ufrmCadProdutos in 'views\ufrmCadProdutos.pas' {frmCadProdutos},
  ufrmCadServicos in 'views\ufrmCadServicos.pas' {frmCadServicos},
  ufrmCadTransportadoras in 'views\ufrmCadTransportadoras.pas' {frmCadTransportadoras},
  ufrmFinContasPagar in 'views\ufrmFinContasPagar.pas' {frmFinContasPagar},
  ufrmFinContasReceber in 'views\ufrmFinContasReceber.pas' {frmFinContasReceber},
  uLocate in 'frameworkFiles\class\uLocate.pas',
  uMess in 'frameworkFiles\class\uMess.pas',
  uSetiConfig in 'frameworkFiles\class\uSetiConfig.pas',
  uSetiConnects in 'frameworkFiles\class\uSetiConnects.pas',
  uSetiFrameworHelp in 'frameworkFiles\class\uSetiFrameworHelp.pas',
  uSetiFramework in 'frameworkFiles\class\uSetiFramework.pas',
  uSetiSearchType in 'frameworkFiles\class\uSetiSearchType.pas',
  uSetiUseful in 'frameworkFiles\class\uSetiUseful.pas',
  ufrmFinFluxoCaixa in 'views\ufrmFinFluxoCaixa.pas' {frmFinFluxoCaixa},
  ufrmStandardItemReg in 'frameworkFiles\views\ufrmStandardItemReg.pas' {frmStandardItemReg},
  ufrmFinBancos in 'frameworkFiles\views\ufrmFinBancos.pas' {frmFinBancos},
  ufrmFinContasBancarias in 'views\ufrmFinContasBancarias.pas' {frmFinContasBancarias},
  ufrmFinFormasPagto in 'views\ufrmFinFormasPagto.pas' {frmFinFormasPagto},
  ufrmFinContas in 'views\ufrmFinContas.pas' {frmFinContas},
  ufrmGerConfiguracoesGerais in 'views\ufrmGerConfiguracoesGerais.pas' {frmGerConfiguracoesGerais},
  ufrmGerCadGrupos in 'views\ufrmGerCadGrupos.pas' {frmGerCadGrupos},
  ufrmGerCadUsuarios in 'views\ufrmGerCadUsuarios.pas' {frmGerCadUsuarios},
  ufrmDpCadFuncionario in 'views\ufrmDpCadFuncionario.pas' {frmDpCadFuncionario},
  ufrmDpCadCargos in 'views\ufrmDpCadCargos.pas' {frmDpCadCargos},
  ufrmDpCadFuncoes in 'views\ufrmDpCadFuncoes.pas' {frmDpCadFuncoes},
  ufrmDpCadComissoes in 'views\ufrmDpCadComissoes.pas' {frmDpCadComissoes},
  ufrmInitialSetting in 'views\ufrmInitialSetting.pas' {frmInitialSetting},
  uClassDAO in 'Dao\uClassDAO.pas',
  uClientesDao in 'Dao\uClientesDao.pas',
  uConfiguracoesGeraisDao in 'Dao\uConfiguracoesGeraisDao.pas',
  uContasBancariasDao in 'Dao\uContasBancariasDao.pas',
  uContasDao in 'Dao\uContasDao.pas',
  uContasPagarDao in 'Dao\uContasPagarDao.pas',
  uContasReceberDao in 'Dao\uContasReceberDao.pas',
  uEmpresasDao in 'Dao\uEmpresasDao.pas',
  uFluxoCaixaDao in 'Dao\uFluxoCaixaDao.pas',
  uFormasPagamentoDao in 'Dao\uFormasPagamentoDao.pas',
  uFornecedoresDao in 'Dao\uFornecedoresDao.pas',
  uInitialSettingDao in 'Dao\uInitialSettingDao.pas',
  uOrcamentosDao in 'Dao\uOrcamentosDao.pas',
  uPedidoCompraDao in 'Dao\uPedidoCompraDao.pas',
  uPedidoVendaDao in 'Dao\uPedidoVendaDao.pas',
  uProdutoGruposDao in 'Dao\uProdutoGruposDao.pas',
  uProdutoMarcasDao in 'Dao\uProdutoMarcasDao.pas',
  uProdutoModelosDao in 'Dao\uProdutoModelosDao.pas',
  uProdutosDao in 'Dao\uProdutosDao.pas',
  uServicosDao in 'Dao\uServicosDao.pas',
  uTransportadoresDao in 'Dao\uTransportadoresDao.pas',
  uUsuariosDao in 'Dao\uUsuariosDao.pas',
  uClassControl in 'controller\uClassControl.pas',
  uClientesControl in 'controller\uClientesControl.pas',
  uConfiguracoesGeraisControl in 'controller\uConfiguracoesGeraisControl.pas',
  uContasBancariasControl in 'controller\uContasBancariasControl.pas',
  uContasControl in 'controller\uContasControl.pas',
  uContasPagarControl in 'controller\uContasPagarControl.pas',
  uContasReceberControl in 'controller\uContasReceberControl.pas',
  uEmpresasControl in 'controller\uEmpresasControl.pas',
  uFluxoCaixaControl in 'controller\uFluxoCaixaControl.pas',
  uFormasPagamentoControl in 'controller\uFormasPagamentoControl.pas',
  uFornecedoresControl in 'controller\uFornecedoresControl.pas',
  uInitialSettingControl in 'controller\uInitialSettingControl.pas',
  uOrcamentosControl in 'controller\uOrcamentosControl.pas',
  uPedidoCompraControl in 'controller\uPedidoCompraControl.pas',
  uPedidoVendaControl in 'controller\uPedidoVendaControl.pas',
  uProdutoGruposControl in 'controller\uProdutoGruposControl.pas',
  uProdutoMarcasControl in 'controller\uProdutoMarcasControl.pas',
  uProdutoModelosControl in 'controller\uProdutoModelosControl.pas',
  uProdutosControl in 'controller\uProdutosControl.pas',
  uServicosControl in 'controller\uServicosControl.pas',
  uTransportadoresControl in 'controller\uTransportadoresControl.pas',
  uUsuariosControl in 'controller\uUsuariosControl.pas',
  uClassModel in 'model\uClassModel.pas',
  uClientesModel in 'model\uClientesModel.pas',
  uConfiguracoesGeraisModel in 'model\uConfiguracoesGeraisModel.pas',
  uContasBancariasModel in 'model\uContasBancariasModel.pas',
  uContasModel in 'model\uContasModel.pas',
  uContasPagarModel in 'model\uContasPagarModel.pas',
  uContasReceberModel in 'model\uContasReceberModel.pas',
  uEmpresasModel in 'model\uEmpresasModel.pas',
  uFluxoCaixaModel in 'model\uFluxoCaixaModel.pas',
  uFormasPagamentoModel in 'model\uFormasPagamentoModel.pas',
  uFornecedoresModel in 'model\uFornecedoresModel.pas',
  uInitialSettingModel in 'model\uInitialSettingModel.pas',
  uOrcamentosModel in 'model\uOrcamentosModel.pas',
  uPedidoCompraModel in 'model\uPedidoCompraModel.pas',
  uPedidoVendaModel in 'model\uPedidoVendaModel.pas',
  uProdutoGruposModel in 'model\uProdutoGruposModel.pas',
  uProdutoMarcasModel in 'model\uProdutoMarcasModel.pas',
  uProdutoModelosModel in 'model\uProdutoModelosModel.pas',
  uProdutosModel in 'model\uProdutosModel.pas',
  uServicosModel in 'model\uServicosModel.pas',
  uTransportadoresModel in 'model\uTransportadoresModel.pas',
  uUsuariosModel in 'model\uUsuariosModel.pas',
  uSetiFormControl in 'frameworkFiles\controller\uSetiFormControl.pas',
  uSetiFormModel in 'frameworkFiles\model\uSetiFormModel.pas',
  uConstant in 'frameworkFiles\class\uConstant.pas',
  uSetiConstantesDB in 'frameworkFiles\class\uSetiConstantesDB.pas',
  uBancosDao in 'Dao\uBancosDao.pas',
  uBancosControl in 'controller\uBancosControl.pas',
  uBancosModel in 'model\uBancosModel.pas',
  uEstoqueAjustesControl in 'controller\uEstoqueAjustesControl.pas',
  uEstoqueAjustesModel in 'model\uEstoqueAjustesModel.pas',
  uEstoqueAjustesDao in 'Dao\uEstoqueAjustesDao.pas',
  uUsuarioGruposDao in 'Dao\uUsuarioGruposDao.pas',
  uUsuarioGruposModel in 'model\uUsuarioGruposModel.pas',
  uUsuarioGruposControl in 'controller\uUsuarioGruposControl.pas',
  ufrmEstoqueAjuste in 'views\ufrmEstoqueAjuste.pas' {frmEstoqueAjuste},
  ufrmOrcamentos in 'views\ufrmOrcamentos.pas' {frmOrcamentos},
  ufrmOrdemServicos in 'views\ufrmOrdemServicos.pas' {frmOrdemServicos},
  ufrmPedidoCompra in 'views\ufrmPedidoCompra.pas' {frmPedidoCompra},
  ufrmPedidoVenda in 'views\ufrmPedidoVenda.pas' {frmPedidoVenda},
  OKCANCL1 in 'c:\program files (x86)\embarcadero\rad studio\9.0\ObjRepos\EN\DelphiWin32\OKCANCL1.PAS' {OKBottomDlg},
  udmInitialSetting in 'dm\udmInitialSetting.pas' {dmInitialSetting: TDataModule},
  udmGen in 'dm\udmGen.pas' {dmGen: TDataModule},
  uMainControl in 'controller\uMainControl.pas',
  uMainModel in 'model\uMainModel.pas',
  uMainDao in 'Dao\uMainDao.pas',
  udmLogin in 'dm\udmLogin.pas' {dmLogin: TDataModule},
  udmComponentsDao in 'dm\udmComponentsDao.pas' {dmComponentsDao: TDataModule},
  ufrmGerCadEmpresa in 'views\ufrmGerCadEmpresa.pas' {frmGerCadEmpresa},
  uFormControlModel in 'frameworkFiles\model\uFormControlModel.pas',
  ufrmGerLogomarca in 'views\ufrmGerLogomarca.pas' {frmGerLogomarca},
  uSetiFormDao in 'frameworkFiles\dao\uSetiFormDao.pas',
  udraftControl in 'frameworkFiles\draft\udraftControl.pas',
  udraftModel in 'frameworkFiles\draft\udraftModel.pas',
  udraftDao in 'frameworkFiles\draft\udraftDao.pas',
  ufrmMasterSearchScreen in 'frameworkFiles\views\ufrmMasterSearchScreen.pas' {frmMasterSearchScreen},
  uMasterSearchScreen in 'frameworkFiles\class\uMasterSearchScreen.pas',
  uSetiMasterClass in 'frameworkFiles\class\uSetiMasterClass.pas',
  uRegions in 'class\uRegions.pas',
  uHelp in 'frameworkFiles\class\uHelp.pas',
  uMasterControl in 'frameworkFiles\controller\uMasterControl.pas',
  uMasterDao in 'frameworkFiles\dao\uMasterDao.pas',
  udmMasterDataModule in 'frameworkFiles\dm\udmMasterDataModule.pas' {dmMasterDataModule: TDataModule};

{$R *.res}

begin
  Application.Initialize;
  frmSplash := TfrmSplash.Create(Nil);
  frmSplash.Show;
  frmSplash.Refresh;
  Sleep(2000);
  frmSplash.Free;
  Application.MainFormOnTaskbar := True;
  Application.CreateForm(TfrmMain, frmMain);
  Application.CreateForm(TdmMasterDataModule, dmMasterDataModule);
  Application.Run;
end.
