USE [sflp]
GO

/****** Object:  Table [dbo].[TBESTABELECIMENTOS]    Script Date: 12/27/2020 4:11:31 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[TBESTABELECIMENTOS](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[NOME] [varchar](100) NULL,
	[ID_TIPO] [int] NULL,
	[STATUS] [char](1) NOT NULL,
 CONSTRAINT [PK_TBESTABELECIMENTOS] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[TBESTABELECIMENTOS] ADD  CONSTRAINT [DF_TBESTABELECIMENTOS_STATUS]  DEFAULT ('T') FOR [STATUS]
GO

ALTER TABLE [dbo].[TBESTABELECIMENTOS]  WITH CHECK ADD  CONSTRAINT [FK_TBESTABELECIMENTOS_TIPOSESTABELECIMENTOS] FOREIGN KEY([ID_TIPO])
REFERENCES [dbo].[TIPOSESTABELECIMENTOS] ([ID])
GO

ALTER TABLE [dbo].[TBESTABELECIMENTOS] CHECK CONSTRAINT [FK_TBESTABELECIMENTOS_TIPOSESTABELECIMENTOS]
GO


