USE [sflp]
GO

/****** Object:  Table [dbo].[TBTIPOSESTABELECIMENTOS]    Script Date: 12/27/2020 4:11:39 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[TBTBTIPOSESTABELECIMENTOS](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[NOME] [varchar](100) NULL,
	[STATUS] [char](1) NOT NULL,
 CONSTRAINT [PK_TBTIPOSESTABELECIMENTOS] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[TBTIPOSESTABELECIMENTOS] ADD  CONSTRAINT [DF_TBTIPOSESTABELECIMENTOS_STATUS]  DEFAULT ('T') FOR [STATUS]
GO
