USE [dbSetiFramework]
GO

SELECT * FROM [dbSetiFramework]..[TBSETICOMPONENT];

--DECLARE @RC int = 1
--DECLARE @TPOPER int = 0
--DECLARE @COMPNAME varchar(100) = 'TPANELTESTE'
--DECLARE @COMPCAPTION varchar(100) = 'Teste'
--DECLARE @COMPFORMID int = 1
--DECLARE @COMPTAG int = 0
--DECLARE @COMPTYPE varchar(30) = 'TPANEL'
--DECLARE @COMPSTATUS char(1) = 'S'
--DECLARE @COMPSEARCHENABLE char(1) = 'S'


DECLARE @RC int = 1
DECLARE @TPOPER int = 4
DECLARE @COMPNAME varchar(100) = ''
DECLARE @COMPCAPTION varchar(100) = ''
DECLARE @COMPFORMID int = -1
DECLARE @COMPTAG int = -1
DECLARE @COMPTYPE varchar(30) = ''
DECLARE @COMPSTATUS char(1) = ''
DECLARE @COMPSEARCHENABLE char(1) = ''


EXECUTE @RC = [dbo].[SP_COMPONENTRECORD] 
   @TPOPER
  ,@COMPNAME
  ,@COMPCAPTION
  ,@COMPFORMID
  ,@COMPTAG
  ,@COMPTYPE
  ,@COMPSTATUS
  ,@COMPSEARCHENABLE
GO


--SELECT * FROM [dbSetiFramework]..[TBSETIFORM];


SELECT * FROM [dbSetiFramework]..[TBSETICOMPONENT];


--TRUNCATE TABLE [dbSetiFramework]..[TBSETICOMPONENT]; 

