INSERT INTO TBFORMCOMPONENTS 
(
     ID                     
    ,PROJECTID              
    ,FORMID                 
    ,COMPONENTNAME          
    ,IDCOMPONENTSTYPE
    ,COMPONENTTAG
    ,COMPONENTCHILD
    ,COMPONENTDADID
    ,DBDATABASENAME
    ,DBTABLENAME
    ,DBFIELDNAME
    ,IDFIELDTYPESDB
    ,DEFAULTHAS             
    ,DEFAULTVALUES          
    ,REQUIRED               
    ,GENERATORHAS           
    ,GENERATORNAME          
    ,ENABLEALLSTATES
    ,ENABLEINITIALSTATE     
    ,ENABLESEARCHSTATE      
    ,ENABLEINSERTSTATE      
    ,ENABLEUPDATESTATE      
    ,ENABLEDELETESTATE      
    ,ENABLEOTHERSTATE       
    ,CHECKALLSTATES         
    ,CHECKINITIALSTATE      
    ,CHECKSEARCHSTATE       
    ,CHECKINSERTSTATE       
    ,CHECKUPDATESTATE       
    ,CHECKDELETESTATE       
    ,CHECKOTHERSTATE        
    ,ITEMINDEXALLSTATES     
    ,ITEMINDEXINITIALSTATE  
    ,ITEMINDEXSEARCHSTATE   
    ,ITEMINDEXINSERTSTATE   
    ,ITEMINDEXUPDATESTATE   
    ,ITEMINDEXDELETESTATE   
    ,ITEMINDEXOTHERSTATAE   
    ,DATRECORD              
    ,DATUPDATE              
    ,DESCRIPTION
) VALUES
(
     /*ID                     INTEGER NOT NULL,*/
    ,/*PROJECTID              INTEGER NOT NULL,*/
    ,/*FORMID                 INTEGER NOT NULL,*/
    ,/*COMPONENTNAME          VARCHAR(50),*/
    ,/*IDCOMPONENTSTYPE       INTEGER,*/
    ,/*COMPONENTCHILD         CHAR(1) DEFAULT 'S',*/
    ,/*COMPONENTDADID         INTEGER,*/
    ,/*DBDATABASENAME         VARCHAR(50),*/
    ,/*DBTABLENAME            VARCHAR(50),*/
    ,/*DBFIELDNAME            VARCHAR(50),*/
    ,/*IDFIELDTYPESDB         INTEGER,*/
    ,/*DEFAULTHAS             CHAR(1) DEFAULT 'N',*/
    ,/*DEFAULTVALUES          VARCHAR(255),*/
    ,/*REQUIRED               CHAR(1) DEFAULT 'N',*/
    ,/*GENERATORHAS           CHAR(1) DEFAULT 'N',*/
    ,/*GENERATORNAME          VARCHAR(50),*/
    ,/*ENABLEALLSTATES        CHAR(1) DEFAULT 'S',*/
    ,/*ENABLEINITIALSTATE     CHAR(1) DEFAULT 'N',*/
    ,/*ENABLESEARCHSTATE      CHAR(1) DEFAULT 'N',*/
    ,/*ENABLEINSERTSTATE      CHAR(1) DEFAULT 'N',*/
    ,/*ENABLEUPDATESTATE      CHAR(1) DEFAULT 'N',*/
    ,/*ENABLEDELETESTATE      CHAR(1) DEFAULT 'N',*/
    ,/*ENABLEOTHERSTATE       CHAR(1) DEFAULT 'N',*/
    ,/*CHECKALLSTATES         CHAR(1) DEFAULT 'N',*/
    ,/*CHECKINITIALSTATE      CHAR(1) DEFAULT 'N',*/
    ,/*CHECKSEARCHSTATE       CHAR(1) DEFAULT 'N',*/
    ,/*CHECKINSERTSTATE       CHAR(1) DEFAULT 'N',*/
    ,/*CHECKUPDATESTATE       CHAR(1) DEFAULT 'N',*/
    ,/*CHECKDELETESTATE       CHAR(1) DEFAULT 'N',*/
    ,/*CHECKOTHERSTATE        CHAR(1) DEFAULT 'N',*/
    ,/*ITEMINDEXALLSTATES     INTEGER DEFAULT -1,*/
    ,/*ITEMINDEXINITIALSTATE  INTEGER DEFAULT -1,*/
    ,/*ITEMINDEXSEARCHSTATE   INTEGER DEFAULT -1,*/
    ,/*ITEMINDEXINSERTSTATE   INTEGER DEFAULT -1,*/
    ,/*ITEMINDEXUPDATESTATE   INTEGER DEFAULT -1,*/
    ,/*ITEMINDEXDELETESTATE   INTEGER DEFAULT -1,*/
    ,/*ITEMINDEXOTHERSTATAE   INTEGER DEFAULT -1,*/
    ,/*DATRECORD              TIMESTAMP DEFAULT current_timestamp,*/
    ,/*DATUPDATE              TIMESTAMP,*/
    ,/*DESCRIPTION            VARCHAR(255)*/
)
